{{- range .Values.externalSecrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "es-{{ .secretName }}"
  namespace: {{ .namespace | default $.Release.Namespace }}
  annotations: null
spec:
  {{- if .refreshInterval }}
  refreshInterval: {{ .refreshInterval }}
  {{- end }}
  {{- if .data }}
  data:
    {{- toYaml .data | nindent 4 }}
  {{- end }}
  {{- if .dataFrom }}
  dataFrom:
    {{- toYaml .dataFrom | nindent 4 }}
  {{- end }}
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: {{ .secretName }}
    {{- if .creationPolicy }}
    creationPolicy: {{ .creationPolicy }}
    {{- end }}
    {{- if .immutable }}
    immutable: {{ .immutable }}
    {{- end }}
    {{- if .template }}
    template:
      {{- toYaml .template | nindent 6 }}
    {{- end }}
{{- end }}
