{{- range .Values.jenkinsCredentials }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
  name: "es-{{ .secretName }}"
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: {{ .secretName }}
    template:
      metadata:
        annotations:
          "jenkins.io/credentials-description": "{{ .description }}"
        labels:
          "jenkins.io/credentials-type": "{{ .type }}"
  {{- if eq .type "usernamePassword" }}
      data:
        username: >- 
          {{ printf "{{ .username | toString }}" }}
        password: >-
          {{ printf "{{ .password | toString }}" }}
  data:
    - secretKey: username
      remoteRef:
        key: {{ .usernameKey | default "jenkins-credentials"}}
        property: {{ .usernameProperty }}
    - secretKey: password
      remoteRef:
        key: {{ .passwordKey | default "jenkins-credentials"}}
        property: {{ .passwordProperty }}

  {{- else if eq .type "basicSSHUserPrivateKey" }}
      data:
        username: >- 
          {{ printf "{{ .username | toString }}" }}
        privateKey: >-
          {{ printf "{{ .privateKey | toString }}" }}
  data:
    - secretKey: username
      remoteRef:
        key: {{ .usernameKey | default "jenkins-credentials"}}
        property: {{ .usernameProperty }}
    - secretKey: privateKey
      remoteRef:
        key: {{ .privatekeyRemoteKey | default "jenkins-credentials" }}
        property: {{ .privatekeyRemoteProperty }}
  {{- end }}
{{- end }}